In [1]:
import numpy as np

In [5]:
k = 3
v = np.array([[9],[-3],[6]])
k * v

array([[27],
       [-9],
       [18]])

In [6]:
v * k

array([[27],
       [-9],
       [18]])

In [7]:
v/k

array([[ 3.],
       [-1.],
       [ 2.]])

In [8]:
# こちらは計算結果がおかしくなる。
k/v

array([[ 0.33333333],
       [-1.        ],
       [ 0.5       ]])

In [11]:
v1 = np.array([[7],[-2],[3]])
v2 = np.array([[3],[5],[-1]])
v1 + v2

array([[10],
       [ 3],
       [ 2]])

In [12]:
v1 - v2

array([[ 4],
       [-7],
       [ 4]])

# 演習問題

- Pythonにおける、ベクトル演算

In [13]:
#1
k = 4
v_1 = np.array([[8],[5]])
k * v_1

array([[32],
       [20]])

In [14]:
# 2
k = 1/3
v_2 = np.array([[-48],[30]])
v_2 * k

array([[-16.],
       [ 10.]])

In [15]:
# 3
v_3_1 = np.array([[10],[10]])
v_3_2 = np.array([[1],[2]])
v_3_1 + v_3_2

array([[11],
       [12]])

In [16]:
# 4
v_4_1 = np.array([[-7],[12]])
v_4_2 = np.array([[-10],[9]])
v_4_1 - v_4_2

array([[3],
       [3]])

In [17]:
# 5
k_5_1 = 1/3
k_5_2 = 2
v_5_1 = np.array([[9],[18],[27]])
v_5_2 = np.array([[1/2],[4],[-3]])
k_5_1 * v_5_1 + k_5_2 * v_5_2

array([[ 4.],
       [14.],
       [ 3.]])

In [20]:
# 6
k_6_1 = 2
k_6_2 = 2j
v_6_1 = np.array([[1],[1j]])
v_6_2 = np.array([[-1j],[1]])
k_6_1 * v_6_1 - k_6_2 * v_6_2

array([[0.+0.j],
       [0.+0.j]])

In [23]:
# 7
# x = np.array([x_1],[x_2])
a = 2/3
b = np.array([[18],[-4]])
x = b / a
x

array([[27.],
       [-6.]])