In [2]:
import numpy as np

In [3]:
k = 5
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
k * A

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [4]:
A * k

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [5]:
A * k == k * A

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
A / k

array([[0.2, 0.4, 0.6, 0.8],
       [1. , 1.2, 1.4, 1.6],
       [1.8, 2. , 2.2, 2.4]])

In [7]:
k / A

array([[5.        , 2.5       , 1.66666667, 1.25      ],
       [1.        , 0.83333333, 0.71428571, 0.625     ],
       [0.55555556, 0.5       , 0.45454545, 0.41666667]])

In [8]:
A / k == k / A

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [9]:
# 行列の加減算
A = np.array([[10,20,30],[40,50,60],[70,80,90]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
A + B

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [10]:
A - B

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [12]:
# Attention
# its wrong
np.array([[10,20,30],[40,50,60],[70,80,90]]) + np.array([2,4,6])

array([[12, 24, 36],
       [42, 54, 66],
       [72, 84, 96]])

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,-3],[-1,5]])
A.dot(B)

array([[ 0,  7],
       [ 2, 11]])

In [18]:
I3 = np.identity(3)
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
I3.dot(A)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [24]:
n = 5
In = np.identity(n)
In

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
P3_12 = np.array([[0,1,0],[1,0,0],[0,0,1]])
P3_13 = np.array([[0,0,1],[0,1,0],[1,0,0]])
p3_23 = np.array([[1,0,0],[0,0,1],[0,1,0]])

In [30]:
P3_12.dot(A)

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [31]:
A.dot(P3_12)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])