In [1]:
import numpy as np

In [2]:
k = 5
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
k * A

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [3]:
A * k

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [5]:
A * k == k * A

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
A / k

array([[0.2, 0.4, 0.6, 0.8],
       [1. , 1.2, 1.4, 1.6],
       [1.8, 2. , 2.2, 2.4]])

In [7]:
k / A

array([[5.        , 2.5       , 1.66666667, 1.25      ],
       [1.        , 0.83333333, 0.71428571, 0.625     ],
       [0.55555556, 0.5       , 0.45454545, 0.41666667]])

In [8]:
A / k == k / A

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [10]:
# 行列の加減算
A = np.array([[10,20,30],[40,50,60],[70,80,90]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
A + B

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [11]:
A - B

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])